#!/bin/bash

export DYLD_LIBRARY_PATH=$PWD:$DYLD_LIBRARY_PATH
export DYLD_INSERT_LIBRARIES="libft_malloc.so"
#export DYLD_FORCE_FLAT_NAMESPACE=1

[ -f libft_malloc_test ] || {
    echo "$0: libft_malloc_test not found" 2>&-
    exit 1
}

for file in $(find tests -maxdepth 1 -name "*.txt")
do
    ./libft_malloc_test < $file | tee test.log
    output=$(tail -1 test.log)
    [ "$output" = "Total: 0 bytes" ] && {
        printf "PASSED <-- %s\n" "$file"
    } || {
        printf "FAILED <-- %s\n" "$file"
    }
    read
done

rm -f test.log

for file in $(find tests -maxdepth 1 -name "*.c");
do
    echo "$file"
	name="${file%.c}"
	gcc -Wall -Wextra -Werror -I. -o "$name" libft_malloc.so "$file"
	"$name"
    read
    rm -f "$name"
done

